server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  task:
      scheduling:
        pool:
          size: 2                    # 定时任务线程池大小
        thread-name-prefix: taotao-task-
  mvc:
    servlet:
      path: /api/v1/campus-taotao
  application:
    name: taotao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/taotao_db?useSSL=false&serverTimezone=UTC
    username: root
    password: xie060106
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: localhost
      port: 6379
      password: dev123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  # 上传限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:com/bit/scmu_taotao/mapper/**/*.xml
  type-aliases-package: com.bit.scmu_taotao.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.bit.scmu_taotao: debug
storage:
  s3:
    #    endpoint: http://localhost:9000
    #    endpoint: http://aijiu.f1.luyouxia.net:15927
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    region: cn-shanghai
    bucket: scmu-taotao
    access-key: ${ALI_ACCESS_KEY}
    secret-key: ${ALI_SECRET_KEY}
    path-style-access: false
    max-file-size: 5MB
    allowed-types: [ jpg, jpeg, png, webp ]
  # 推荐系统配置(没用上）
  recommendation:
    # 推荐权重配置（总分100）
    category-weight: 30.0          # 分类偏好权重
    favorite-weight: 20.0          # 收藏权重（每个收藏+20分）
    view-count-weight: 25.0        # 点击量权重（总额度25分）
    recent-publish-bonus: 25.0     # 最近发布加分（30天内，总额度25分）

    # 缓存配置
    hot-cache-count: 50            # 热门缓存数量
    hot-cache-expire-hours: 1      # 热门缓存过期时间（小时）

    # 数据生命周期配置
    browse-history-days: 30        # 浏览历史保留天数
    click-anti-spam-hours: 1       # 点击防刷时间窗口（小时）

goods:
  # 敏感词库（用逗号分隔）
  sensitive-words: "高仿,A货,套现,刷单,假证,代考,作弊,毒品,枪支,烟草,电子烟,色情,催情,迷药,走私,假药,医疗器械,堕胎药,流产药"


